name: CI Pipeline - Spring Boot Tests

on:
  push:
    branches: [ "master", "develop" ] # Se ejecuta cada vez que subís código a main o develop
  pull_request:
    branches: [ "master" ] # Se ejecuta cuando intentás hacer un Pull Request

jobs:
  testeo-y-verificacion:
    # Levanta una máquina virtual en la nube con la última versión de Ubuntu (Linux)
    runs-on: ubuntu-latest

    # PASO A PASO
    steps:

      # Paso A: Descargar tu repositorio de GitHub a esta máquina virtual
      - name: 1️⃣ Checkout del código
        uses: actions/checkout@v4

      # Paso B: Instalar tu versión específica de Java
      - name: 2️⃣ Configurar Java JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto' # Usamos la versión de Java de Amazon (muy estándar en la industria)
          cache: maven # Magia negra que hace que la segunda vez que corra el robot, lo haga el doble de rápido

      # Paso C: Darle permiso a Linux para ejecutar Maven
      - name: 3️⃣ Dar permisos de ejecución al Maven Wrapper
        run: chmod +x mvnw

      # Paso D: Ejecutar
      - name: 4️⃣ Ejecutar Tests Unitarios
        run: ./mvnw test